build.rs, src/lib.rs, tests/bigquery_allof.rs, tests/bigquery_array.rs, tests/bigquery_atomic.rs, tests/bigquery_map.rs, tests/bigquery_object.rs, tests/bigquery_oneof.rs
This passes the `bigquery_atomic` test suite, run with the following command:
`cargo test --no-fail-fast bigquery`
This also runs all of the other tests, most of which are failing. 
---
The most significant hurdle here is working with the borrow checker. When recursively generating values, the values must be cloned/moved during the matching process in order to prevent a "use after free" or "variable out of scope" issue. My limited fluency with the standard library means that there are quite a few calls to `.to_owned()` and `.into()`.
https://doc.rust-lang.org/std/vec/struct.Vec.html
https://doc.rust-lang.org/rust-by-example/primitives/tuples.html
https://users.rust-lang.org/t/to-string-vs-to-owned-for-string-literals/1441
https://doc.rust-lang.org/std/collections/struct.HashSet.html
=> Handle simple types when converting to BigQuery schema

.gitignore, Cargo.lock, Cargo.toml, src/main.rs
This uses https://github.com/clap-rs/clap to add a minimal command line interface. The program will ideally work like `jq` by reading from an IO stream and writing out to stdout.
From `cargo run -- --help`:
```
amiyaguchi-vxjgh5:jsonschema-transpiler amiyaguchi$ cargo run -- --help
Compiling jsonschema_transpiler v0.1.0 (/Users/amiyaguchi/Work/jsonschema-transpiler)
Finished dev [unoptimized + debuginfo] target(s) in 1.88s
Running `target/debug/jsonschema_transpiler --help`
jst 0.1
Anthony Miyaguchi <amiyaguchi@mozilla.com>
USAGE:
jsonschema_transpiler [OPTIONS]
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
-f, --from-file <FILE>
```
=> Add a command-line interface via clap

src/ast.rs, src/lib.rs, src/main.rs
This adds an intermediate AST to transform into and from. This captures enough information to be useful for constructing both avro and bigquery schemas. 
There are some other changes that are tagging along due to refactoring:
* A change caught by `cargo fmt`
* Minor clean-up in `convert_bigquery`
=> Add an abstract schema tree 

src/bigquery.rs, src/lib.rs
This adds a grammar for BigQuery. There are a couple noteworthy bits in this file.
* Using `#[serde(tag="type")]` on all enums does the correct thing when serializing. This saved time writing a custom serializer.
* The inverse is not true, so there is a custom deserializer for the `Type` enum. This is to handle the case `{"type": "INT64"}` and the ilk -- this is actually a `Type::Atom(Atom::Int64)`. The deserializer first tries to deserialize as an atom, and then matches against the other types.
* There is a custom serializer/deserializer for the `Record` struct. For ergonomics, I've treated the BigQuery field as a HashMap instead of a Vector. This assumption breaks if the type does not have a name...
=> Add a grammar and serde for bigquery

src/jsonschema.rs, src/lib.rs
This adds serde for JSONSchema that can be used to transform into and out of the ast module.
I referenced the JSON Schema v4 meta-schema when building up the grammar: http://json-schema.org/draft-04/schema. It provides a useful skeleton for how to create the data structure.
There are some interesting bits to serde attributes that were also pain points -- I'll point them out in a self-review.
=> Add grammar for JSONSchema

src/ast.rs
Fixes #16. This adds a union type to the AST that can be mapped to the JSON Schema's oneOf construct. This also adds defaults to the data structure.
=> Fix #16: Add Union type to ast::Type

src/ast.rs, src/jsonschema.rs
This fixes #19.
This PR adds a few things to the ast module:
* Derive `Clone` for most of the structs
* Implements a `Union::collapse` method which flattens union types
* Implements a `Tag::infer_name` method for adding missing names to objects
* Moves `Into<ast::Tag> for jsonschema::Tag` to `From<jsonschema::Tag> for ast::Tag`, which gives `into` for free.
=> Collapse Type::Union into a flattened type

src/ast.rs, src/bigquery.rs, src/jsonschema.rs
This fixes #13. 
* Adds public visibility for ast structs
* Adds implementation of `From<ast::Tag> for bigquery::Tag`
* Adds tests
=> Implement `From<ast::Tag> for bigquery::Tag` 

Cargo.lock, Cargo.toml, build.rs, src/lib.rs
This pins dependencies to known versions.
=> Specify version numbers in cargo manifest

src/avro.rs, src/lib.rs
This fixes #14. I learned from the other grammars, making the avro schema cleaner than the other implementations. The spec was useful during this stage.
https://avro.apache.org/docs/current/spec.html
* Unions are implemented using standard serde attributes. In the `jsonschema` module, I left the type as a `Value` and implemented a helper function to disambiguate `Type` from a `Vec<Type>`.
https://github.com/acmiyaguchi/jsonschema-transpiler/blob/2de4ca494d8488fac1d4041ddcf88d189bbf3671/src/jsonschema.rs#L79-L85
* I also avoided the issue with flattening a nested enum by treating the enum as an untagged union. I ran into issues treating the main `Type` as a tagged-union and adding the `serde(tag = "type")` attribute on all involved types. This will flatten to the correct json format, but …
=> Implement grammar for Avro

Cargo.lock, Cargo.toml, src/ast.rs, src/avro.rs, src/bigquery.rs, src/jsonschema.rs, src/lib.rs
This PR, along with [mps#291](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/291) and [mps#290](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/290) fixes generation of Avro schemas.
* Fixed the type of record fields. They were originally flattened to look like this:
```json
{
"type":"record",
"fields":[
{
"name":"foo",
"type":"record",
"fields":[
{
"name":"bar",
"type":"null"
}
]
}
]
}
```
They should actually be in the following simplified form:
```json
{
"type":"record",
"fields":[
{
"name":"foo",
"type": {
"name": "foo",
"type":"record",
"fields":[
{ 
"name":"bar",
"type":"null"
}
]
}
}
]
}
```
However, this forces the more verbose form of simple types due to serialization.
* Fixed union types by using vectors directly e.g. `{"type": ["null", …
=> Fix namespace generation in Avro schemas

Cargo.lock, Cargo.toml, README.md, src/main.rs
The changes the package name from `jsonschema_transpiler` to `jsonschema-transpiler`. The application now reads from stdin when no argument are provided or from a file when a positional argument is passed. This should make it easier to run the tool in bash via xargs and pipelining.
I've also updated the README to include some example usage that shows what the input and outputs look like.
=> Modify cli name and options; bump version to 0.2

src/bigquery.rs, tests/resources/atomic.json, tests/transpile_bigquery.rs
TIMESTAMP type can be partioned on, but DATETIME cannot.
I ain't angry, but I'm angry.
=> Use timestamp rather than datetime in bq

build.rs
This makes working on these files in your editor of choice a bit easier, because you don't need to close and/or delete workspace files (e.g. `.swp` files in vim).
=> Ignore hidden test resource files

README.md, src/main.rs
This adds a section for publishing to crates.io. It also updates the status badge and removes the version number from the cli help page.
=> Add instructions on publishing to crates.io

Cargo.lock, Cargo.toml, src/bigquery.rs, src/lib.rs, tests/resources/array.json, tests/resources/atomic.json, tests/resources/map.json, tests/resources/object.json, tests/resources/oneof.json, tests/transpile_bigquery.rs
This will fix #51 by making the starting the resulting BigQuery schema as a list of elements.
EDIT: This is ready for review. See https://github.com/mozilla/jsonschema-transpiler/pull/61#issuecomment-488427937
---
There are currently 5 failures:
```
failures:
bigquery_test_object_empty_record
bigquery_test_oneof_object_merge
bigquery_test_oneof_object_merge_nullability
bigquery_test_oneof_object_merge_with_complex
bigquery_test_oneof_object_with_atomics
test result: FAILED. 23 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out
```
In particular, the edge case that needs to be captured is the empty schema. Should the resulting table be an empty schema i.e. `[]`?
```json
{
"description": [
"Empty structs are not supported in BigQuery, so we treat them ",
"as empty documents."
], …
```
=> Extract root columns from BigQuery schema

Cargo.lock, Cargo.toml, build.rs, src/ast.rs, src/avro.rs, src/bigquery.rs, src/jsonschema.rs, src/lib.rs, src/main.rs, src/traits.rs, tests/resolve_method.rs, tests/resources/array.json, tests/resources/atomic.json, tests/resources/map.json, tests/resources/object.json, tests/resources/oneof.json, tests/transpile_avro.rs, tests/transpile_bigquery.rs
This PR should (mostly) fix #75.
The approach in this pull-request is as follows:
---
At a high-level, we should be dropping fields during transpilation if the subschema is incompatible (tuple validation) or if the schema is underspecified (an empty object). This adds error-handling when translating between schemas (`ast -> bigquery` and `ast -> avro` in particular).
I've tried to keep the changes minimal. I've left most of the unit-tests alone aside from refactoring so it is easier to add the context variable. I've added a `compatible` field to the `TestCase` object which makes it easy to retrofit the existing tests to determine whether fields will be dropped with the new error handling methods.
See https://github.com/mozilla/jsonschema-transpiler/pull/76#issuecomment-505630943 for a …
=> Add a flag to drop fields instead of casting

Cargo.lock, Cargo.toml, src/ast.rs, src/avro.rs, src/bigquery.rs, src/jsonschema.rs, tests/resources/translate/atomic.json, tests/transpile_avro.rs, tests/transpile_bigquery.rs
=> Support bytes as a data type

Cargo.lock, Cargo.toml, src/ast.rs
> I don't understand why this is setting `self.nullable = true` both here and on 537
_Originally posted by @relud in https://github.com/mozilla/jsonschema-transpiler/pull/85_
Thanks for pushing on this one, it's certainly a redundant path. I should have spent more time looking it over.
=> Remove redundant code path

Cargo.lock, Cargo.toml, scripts/mps-generate-avro-data-helper.py, scripts/mps-verify-nested-list.sh, src/ast.rs, src/avro.rs, src/bigquery.rs, src/jsonschema.rs, src/lib.rs, tests/force_nullable.rs, tests/resources/translate/array.json, tests/transpile_avro.rs, tests/transpile_bigquery.rs
Nested lists are not handled correctly.
```bash
$ echo '{
"type": "array",
"items": {
"type": "array",
"items": {
"type": "array",
"items": [
{"type": "integer"}
],
"additionalItems": false
}
}
}' | jsonschema-transpiler --type bigquery --tuple-struct
```
results in 
```json
[
{
"fields": [
{
"mode": "REQUIRED",
"name": "f0_",
"type": "INT64"
}
],
"mode": "REPEATED",
"name": "root",
"type": "RECORD"
}
]
```
This PR fixes this so there is an intermediate layer that can be used for unnesting.
```json
[
{
"fields": [
{
"fields": [
{
"mode": "REQUIRED",
"name": "f0_",
"type": "INT64"
}
],
"mode": "REPEATED",
"name": "list",
"type": "RECORD"
}
],
"mode": "REPEATED",
"name": "root",
"type": "RECORD"
}
]
```
See this gist for the result of the verification script: …
=> Nested list

src/ast.rs, src/avro.rs, src/bigquery.rs, src/jsonschema.rs, src/lib.rs, src/main.rs, tests/resources/translate/atomic.json, tests/resources/translate/map.json, tests/resources/translate/object.json, tests/transpile_avro.rs, tests/transpile_bigquery.rs
This addresses https://github.com/mozilla/jsonschema-transpiler/issues/58.
I also fixed some formatting and clippy issues in the process. For now I extended existing tests but I could also create separate test cases for testing the description propagation if wanted.
=> Propagate "description" from json schema to BigQuery schema

.circleci/config.yml, Cargo.lock, Cargo.toml, README.md, src/ast.rs, src/casing.rs, src/lib.rs
This PR uses regex and [heck](https://docs.rs/heck/0.3.3/heck/) as replacements for [oniguruma](https://github.com/rust-onig/rust-onig). Oniguruma is used to perform the snake casing logic in a language independent way. The rules were originally sourced from heck, and are fully compatible with the casing tests.
This should reduce build times (since we no longer have to compile oniguruma from the C sources) and make it easier to compile the package to wasm.
=> Use pure rust libraries for regex and snakecasing

README.md
Updated command examples to represent current output. I've run the example commands and I got a slightly different output for the `jsonschema-transpiler` examples. This proposed updating the README to reflect that.
Package version:
```bash
$ cargo install --list
jsonschema-transpiler v1.10.0:
jsonschema-transpiler
```
Below is the output I get when running the examples:
```bash
echo $schema | jq
{
"type": "object",
"properties": {
"foo": {
"type": "boolean"
}
}
}
```
```bash
echo $schema | jsonschema-transpiler --type avro
{
"fields": [
{
"default": null,
"name": "foo",
"type": [
{
"type": "null"
},
{
"type": "boolean"
}
]
}
],
"name": "root",
"type": "record"
}
```
```bash
$ echo $schema | jsonschema-transpiler --type bigquery
[
{
"mode": "NULLABLE",
"name": "foo",
"type": "BOOL"
}
]
```
=> Updated command examples to represent current output
